### ISSUE TITLE
Crash on launcher start

### ISSUE THREAD

**Issue by samansalamat** [OpenLauncherTeam/openlauncher#191]
**when I try to run the launcher i get the following error:**
LOGCAT:
 --------- beginning of crash
07-15 11:49:46.997 5783-5783/com.benny.openlauncher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.benny.openlauncher, PID: 5783
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.benny.openlauncher/com.benny.openlauncher.activity.Home}: android.view.InflateException: Binary XML file line #11: Binary XML file line #19: Error inflating class com.benny.openlauncher.core.widget.BaseSearchBar
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #19: Error inflating class com.benny.openlauncher.core.widget.BaseSearchBar
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                          at com.benny.openlauncher.core.activity.Home.onCreate(Home.java:131)
                                                                          at com.benny.openlauncher.activity.Home.onCreate(Home.java:94)
                                                                          at android.app.Activity.performCreate(Activity.java:6237)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                       Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.benny.openlauncher.core.widget.BaseSearchBar
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                          at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at com.benny.openlauncher.core.activity.Home.onCreate(Home.java:131) 
                                                                          at com.benny.openlauncher.activity.Home.onCreate(Home.java:94) 
                                                                          at android.app.Activity.performCreate(Activity.java:6237) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at com.benny.openlauncher.core.activity.Home.onCreate(Home.java:131) 
                                                                          at com.benny.openlauncher.activity.Home.onCreate(Home.java:94) 
                                                                          at android.app.Activity.performCreate(Activity.java:6237) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                       Caused by: java.lang.ExceptionInInitializerError
                                                                          at com.benny.openlauncher.core.widget.BaseSearchBar.<init>(BaseSearchBar.java:71)
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at com.benny.openlauncher.core.activity.Home.onCreate(Home.java:131) 
                                                                          at com.benny.openlauncher.activity.Home.onCreate(Home.java:94) 
                                                                          at android.app.Activity.performCreate(Activity.java:6237) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                       Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'Y'
                                                                          at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
                                                                          at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
                                                                          at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
                                                                          at com.benny.openlauncher.core.widget.BaseSearchBar$Mode.<clinit>(BaseSearchBar.java:47)
                                                                          at com.benny.openlauncher.core.widget.BaseSearchBar.<init>(BaseSearchBar.java:71) 
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at com.benny.openlauncher.core.activity.Home.onCreate(Home.java:131) 
                                                                          at com.benny.openlauncher.activity.Home.onCreate(Home.java:94) 
                                                                          at android.app.Activity.performCreate(Activity.java:6237) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by MFlisar** [comment]
Solved in my pending pull request

**Comment by debarpan** [comment]
It is not solved. I just tried your latest and the error is still there.

**Comment by MFlisar** [comment]
Did not see this line `java.lang.IllegalArgumentException: Unknown pattern character 'Y'` first and thought it's another error.

For me everything works as expected, but I saw that I should encapsle hard coded strings in the date format in `' `. Can you try if my last change helped?

**Comment by samansalamat** [comment]
tnx its been fixed
